List missing builtins
serge-sans-paille/penty pull request #21
Opened 2020-11-29 19:44 UTC by serge-sans-paille

except exceptions, they're another story

2020-12-06 12:10 UTC, serge-sans-paille commented
@lsix ready for review!

2020-12-07 08:56 UTC, lsix requested changes
Fast pass (during a meeting), I have not been through the tests yet.

2020-12-07 08:56 UTC, lsix commented on penty/pentypes/builtins.py
> +        if not issubclass(mod, int):
I guess you meant `issubclass(_astype(mod), int)`

2020-12-07 08:56 UTC, lsix commented on penty/pentypes/builtins.py
> +    print(ty)
this debugging message should be removed.

2020-12-07 08:56 UTC, lsix commented on penty/pentypes/builtins.py
> +        print('hashing', key)
This one also

2020-12-11 13:37 UTC, merged